export const CODE_STATUS = {
    USER_NOT_EXISTS: "USER_NOT_EXISTS",
    INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
    INCORRECT_FIELDS: "INCORRECT_FIELDS",
    INVALID_TOKEN: "INVALID_TOKEN",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
    ALL_CONSTRUCTION_COMMENTS_SUCCESS: "ALL_CONSTRUCTION_COMMENTS_SUCCESS",
    ALL_CONSTRUCTION_NOTES_SUCCESS: "ALL_CONSTRUCTION_NOTES_SUCCESS",
    ALL_NEWS_SUCCESS: "ALL_NEWS_SUCCESS",
    CONSTRUCTION_NOTE_ADDED_SUCCESS: "CONSTRUCTION_NOTE_ADDED_SUCCESS",
    CONSTRUCTION_NOTE_ALREADY_EXISTS: "CONSTRUCTION_NOTE_ALREADY_EXISTS",
    CONSTRUCTION_COMMENT_ADDED_SUCCESS: "CONSTRUCTION_COMMENT_ADDED_SUCCESS",
    CONSTRUCTION_COMMENT_ALREADY_EXISTS: "CONSTRUCTION_COMMENT_ALREADY_EXISTS"
}