export const CODIGO_STATUS = {
    ADMIN: {
        LOGIN_USUARIO_INEXISTENTE: "LOGIN_USUARIO_INEXISTENTE",
        LOGIN_CREDENCIAIS_INVALIDAS: "LOGIN_CREDENCIAIS_INVALIDAS",
        LOGIN_SUCESSO: "LOGIN_SUCESSO",
        LOGOUT_SUCESSO: "LOGOUT_SUCESSO"
    },
    SESSAO: {
        TOKEN_INVALIDO: "TOKEN_INVALIDO",
    },
    CORPO: {
        CAMPOS_INCORRETOS: "CAMPOS_INCORRETOS"
    },
    OBRA: {
        OBRA_NAO_EXISTE: "OBRA_NAO_EXISTE",
        OBRAS_SUCESSO: "OBRAS_SUCESSO",
        OBRA_SUCESSO: "OBRA_SUCESSO",
        NOTA_CRIADA_SUCESSO: "NOTA_CRIADA_SUCESSO",
        NOTA_JA_EXISTE: "NOTA_JA_EXISTE",
        COMENTARIO_CRIADO_SUCESSO: "COMENTARIO_CRIADO_SUCESSO",
        COMENTARIOS_OBRA_SUCESSO: "COMENTARIOS_OBRA_SUCESSO",
        NOTAS_OBRA_SUCESSO: "NOTAS_OBRA_SUCESSO"
    },
    NOTICIA: {
        NOTICIA_NAO_EXISTE: "NOTICIA_NAO_EXISTE",
        NOTICIAS_SUCESSO: "NOTICIAS_SUCESSO",
        NOTICIA_ALTERADA_SUCESSO: "NOTICIA_ALTERADA_SUCESSO",
        NOTICIA_DELETADA_SUCESSO: "NOTICIA_DELETADA_SUCESSO",
        NOTICIA_CRIADA_SUCESSO: "NOTICIA_CRIADA_SUCESSO"
    },
    ERRO: {
        PROBLEMA_INESPERADO: "PROBLEMA_INESPERADO"
    }
}