export const CODIGO_STATUS = {
    ADMIN: {
        LOGIN_CREDENCIAIS_INVALIDAS: "ADMIN_LOGIN_CREDENCIAIS_INVALIDAS",
        LOGIN_SUCESSO: "ADMIN_LOGIN_SUCESSO",
        LOGOUT_SUCESSO: "ADMIN_LOGOUT_SUCESSO"
    },
    SESSAO: {
        TOKEN_INVALIDO: "SESSAO_TOKEN_INVALIDO",
        TOKEN_INDEFINIDO: "SESSAO_TOKEN_INDEFINIDO"
    },
    CORPO: {
        CAMPOS_INCORRETOS: "CORPO_CAMPOS_INCORRETOS"
    },
    OBRA: {
        ALTERADA_SUCESSO: "OBRA_ALTERADA_SUCESSO",
        CRIADA_SUCESSO: "OBRA_CRIADA_SUCESSO",
        NAO_EXISTE: "OBRA_NAO_EXISTE",
        SUCESSO: "OBRAS_SUCESSO",
        SELECIONADA_SUCESSO: "OBRA_SELECIONADA_SUCESSO",
        DELETADA_SUCESSO: "OBRA_DELETADA_SUCESSO",
    },
    FILTRO_OBRAS: {
        CATEGORIA_NAO_EXISTE: "FILTRO_OBRAS_CATEGORIA_NAO_EXISTE",        
        TIPO_ORDEM_NAO_EXISTE: "FILTRO_OBRAS_TIPO_ORDEM_NAO_EXISTE",
        QUANTIDADE_INVALIDA: "FILTRO_OBRAS_QUANTIDADE_INVALIDA"    
    },
    COMENTARIO: {
        CRIADO_SUCESSO: "COMENTARIO_CRIADO_SUCESSO",
        SUCESSO: "COMENTARIOS_OBRA_SUCESSO",
    },
    NOTA: {
        CRIADA_SUCESSO: "NOTA_CRIADA_SUCESSO",
        JA_EXISTE: "NOTA_JA_EXISTE",
        SUCESSO: "NOTAS_OBRA_SUCESSO",
    },
    NOTICIA: {
        NAO_EXISTE: "NOTICIA_NAO_EXISTE",
        SUCESSO: "NOTICIAS_SUCESSO",
        ALTERADA_SUCESSO: "NOTICIA_ALTERADA_SUCESSO",
        DELETADA_SUCESSO: "NOTICIA_DELETADA_SUCESSO",
        CRIADA_SUCESSO: "NOTICIA_CRIADA_SUCESSO"
    },
    ERRO: {
        PROBLEMA_INESPERADO: "ERRO_PROBLEMA_INESPERADO"
    },
    ESTATISTICA_OBRAS: {
        SITUACAO_SUCESSO: "ESTATISTICA_OBRAS_SITUACAO_SUCESSO",
        CATEGORIA_SUCESSO: "ESTATISTICA_OBRAS_CATEGORIA_SUCESSO",
        ANO_SUCESSO: "ESTATISTICA_OBRAS_ANO_SUCESSO",
        BALANCO_SUCESSO: "ESTATISTICA_OBRAS_BALANCO_SUCESSO",
        GASTO_ANUAL_SUCESSO: "ESTATISTICA_OBRAS_GASTO_ANUAL_SUCESSO"
    }
}